### ISSUE TITLE
Clarify request for information and PRs from TOPS panelists

### ISSUE THREAD

**Issue by colliand** [nasa/Transform-to-Open-Science#278]
During the TOPS panel meeting on 2022-10-05 at JPL, @bello-mart-isabella proposed a "GitHub activity" wherein panelists were encouraged to contribute to this repository via pull requests. What kind of information does TOPS want us to contribute?

**Comment by cgentemann** [comment]
We are looking for community input and help developing our [resources](https://github.com/nasa/Transform-to-Open-Science/tree/main/resources). How do our open science cookbooks look? Does this presentation make sense / resonate with you? In our templates, we are looking for help developing comprehensive information on how to organize and run different types of events. Thanks!

**Comment by bressler95tops** [comment]
According to PR #297 the resources folder was deleted, and open science cookbook was moved and in PR #364 the open science cookbook directory was removed in favor of JupyterBook.  This may still be something that changes but as of now that information should now be located at [this repository](https://github.com/nasa/Transform-to-Open-Science-Book).  But feel free to propose PR's to either repository.  Figured I would comment on this issue and mark it as resolved since it was still open.
