### ISSUE TITLE
Develop compendium for TOPS resources

### ISSUE THREAD

**Issue by Earth2Ivey** [nasa/Transform-to-Open-Science#31]

**Comment by bello-mart-isabella** [comment]
This has been completed and can now be found at https://nasa.github.io/Transform-to-Open-Science/Open_Science_Cookbook/readme.html

**Comment by usethedata** [comment]
@bello-mart-isabella  -- the link in the above comment gives a page not found error for me.

**Comment by usethedata** [comment]
Question that I think is relevant to this issue: To what extent has the TOPS work considered (and potentially collaborated with) the FORCE11 efforts in Open Science, such as the upcoming summer 2023 Scholarly Communication Institute  https://force11.org/fsci/post/course-list-with-abstracts-2022/?mc_cid=1d6189bb95&mc_eid=1be1457d69

**Comment by bressler95tops** [comment]
Closing out this issue due to inactivity, this also seems to be in reference to the [JupyterBook](https://nasa.github.io/Transform-to-Open-Science-Book/) that once existed on the main repository.  Feel free to open another issue / reopen this one if you have any additional concerns and I can run it by the project office.
