### ISSUE TITLE
TOPS Champions

### ISSUE THREAD

**Issue by cgentemann** [nasa/Transform-to-Open-Science#539]
@bressler1995 @bressler95tops 

Is it possible to organize the champions into lead / module sections like what was done for the 2022 teams please? (last half of this page - instead of just listing them by center). I am often looking for people to contact about the modules and I can't tell who to reach out to easily from NASA.
Thanks!
 
https://github.com/nasa/Transform-to-Open-Science/blob/main/docs/Area2_Capacity_Sharing/Open-Science-101/curriculum_leads.md

**Comment by bressler95tops** [comment]
Sounds good Chelle, I will look into this as well and will confirm with others to make sure I update it accurately

**Comment by bressler95tops** [comment]
@cgentemann I reached out to Diana for this since the only list we have is by center at the moment, but she let me know that she would look into contacting the module teams to get an updated list of who participated so we could figure out organizing it in this way.  I will keep this flagged and update you once we can make the modification

**Comment by bressler95tops** [comment]
Posting an update on this since it has been a little bit.  Diana and myself have reached out to the module leads and we are just waiting on the remaining names for module 1, we have the names for all the other modules.  A revised list should get pushed out soon.

**Comment by bressler95tops** [comment]
It would seem that the module leads were / champions were updated to match this structure from Diana's spreadsheet we worked on together.  Let me know if anything else needs to be addressed with this @cgentemann
