### ISSUE TITLE
OS101 Module 2, Lesson 1 - typo in image

### ISSUE THREAD

**Issue by NPalopoli** [nasa/Transform-to-Open-Science#639]
In [this image](https://github.com/nasa/Transform-to-Open-Science/blob/open-science-101/Module_2/images/media/image9.png) in Module 2, Lesson 1, there's a missing 'e' at the end of 'BSD 3-Clause' in the top-right 'TL-DR' box.

(Note: edited with correct link)

**Comment by SLLDeC** [comment]
@NPalopoli The image doesn't show. The link throws a 'Not Found' message.

**Comment by bressler95tops** [comment]
Thank you for pointing that out @NPalopoli. We will be reviewing curriculum suggestions hopefully within the next couple weeks as we make some adjustments to the first release and citation information so definitely let us know if you find anything else and stay tuned.

**Comment by bressler95tops** [comment]
@katblanchette I just corrected the link for Nicholas's issue submission.  This one also was fairly easy to open up in Illustrator, do an image trace and add the letter. I can upload the source to the internal graphics folder you shared so we all have it for easy edits since this didn't seem to be included with the existing sources.  I will replace it in the content and update here, I just figured I would give some background to the fix first.
![M2L1BSDClause-01](https://github.com/nasa/Transform-to-Open-Science/assets/137207208/3eeae388-74ac-4fa0-b1dc-56dd2c74ffb2)

**Comment by katblanchette** [comment]
@bressler95tops - Thank you for the information and thank you for adding the "e" to Claus in the image. Please move forward with replacing image with the new image in GitHub, and the OS101 Team will also notify the Developers and update the ILT slides. We will notify you when these files are updated.

**Comment by bressler95tops** [comment]
Thanks @katblanchette.  I have gone ahead and made the replacement.  As usual, the PR has been addressed in PR #772.  You can see exact details in the [files changed tab](https://github.com/nasa/Transform-to-Open-Science/pull/772/files).

**Comment by bressler95tops** [comment]
I will also add those images to the locations you mentioned.

**Comment by bressler95tops** [comment]
@NPalopoli @katblanchette Thank you for your patience on this, this change is completed on both the MOOC and the GitHub version of OS101.  We will go ahead and mark this as closed.
