### ISSUE TITLE
Incorrect proprietary data format question

### ISSUE THREAD

**Issue by ccorti87** [nasa/Transform-to-Open-Science#708]
The question about Microsoft Word as a proprietary file format in the Open Data module is technically not correct: .docx is a open standard since 2006.
Sources:
https://en.m.wikipedia.org/wiki/Office_Open_XML_file_formats
https://en.m.wikipedia.org/wiki/Proprietary_file_format#Formerly_proprietary
https://en.m.wikipedia.org/wiki/Microsoft_Open_Specification_Promise

![IMG_20240401_234237](https://github.com/nasa/Transform-to-Open-Science/assets/22922350/b7c48208-66a7-4dc4-8792-f24ccd54a271)

I suggest using another file format as example for a proprietary data format, e.g., IDL save file.
Source: https://pages.physics.wisc.edu/~craigm/idl/savefmt/node1.html

**Comment by bressler95tops** [comment]
Thank you for submitting this suggestion about the Open Data module @ccorti87. We are actively working on a review process for OS101 and we should be reviewing these in the coming weeks. Stay tuned and feel free to keep submitting more suggestions in the meantime.

**Comment by katblanchette** [comment]
@bressler95tops  - 1st Update: On the M3, multiple choice assessment question #1, replace the "Microsoft Word (.doc/ .docx)" answer with "Adobe Photoshop (.psd)". 2nd Update: M3, L3, with the section titled "Non Data Open Formats", remove Microsoft and place it under "Open Data Format Examples".

**Comment by bressler95tops** [comment]
@katblanchette I have addressed the second part of this in M3L3.  Since the first part relates to M3's assessment questions, we don't have that content on the GitHub version although that could change in the future depending on what direction we go in for future releases. The PR addressing this issue is PR #760.  You can see precise changes in the ['files changed'](https://github.com/nasa/Transform-to-Open-Science/pull/760/files) tab.  Let me know when the MOOC developers have had a chance to implement this.

**Comment by bressler95tops** [comment]
@ccorti87 @katblanchette thank you for your patience.  This change is complete both on the GitHub version of OS101 and on the MOOC, and likewise this issue can now be closed out.  We appreciate your contributing to OS101!
