### ISSUE TITLE
Create an open science corpus/literature database

### ISSUE THREAD

**Issue by rmcgranaghan** [nasa/Transform-to-Open-Science#79]
Compile articles, blogs, books, and other writing related to open science into a corpus that can be searched by open scientists and explored with Natural Language Processing algorithms to understand trends and gaps. Could use something like a shared online Zotero library (zotero.org/) to begin.

**Comment by PeerHerholz** [comment]
Would this be related to #142 or independent?

**Comment by bello-mart-isabella** [comment]
This was incorporated into our Open Science Guidebook and can now be found here: https://nasa.github.io/Transform-to-Open-Science/Open_Science_Cookbook/reading_list.html

**Comment by bressler95tops** [comment]
The reading list that Isabella mentioned is now located at the [reading list page](https://nasa.github.io/Transform-to-Open-Science-Book/Open_Science_Cookbook/reading_list.html) on the Jupyter Book [repository](https://github.com/nasa/Transform-to-Open-Science-Book).  I will mark this specific issue as resolved since it has not seen further activity but feel free to make suggestions on the content or presentation of the reading list.
