### ISSUE TITLE
Add a citation file to the repository

### ISSUE THREAD

**Issue by juanpflores** [nasa/Transform-to-Open-Science#802]
Create a [CITATION](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files) file to make referencing this repository easier.

> NASA TOPS Open Science 101 Curriculum Development Team. (2023). NASA TOPS Open Science 101 version 1.0.0. Zenodo. DOI: 10.5281/zenodo.10161527.

**Comment by bressler95tops** [comment]
Thank you @juanpflores we do have a citation file which you can retrieve the citation strings when viewing the [open-science-101](https://github.com/nasa/Transform-to-Open-Science/tree/open-science-101) branch as so:

![image](https://github.com/user-attachments/assets/1abed900-6def-42ab-b237-56205a828f84)

However it has been some time since this file was last updated.  So it may be worth it for us to give it a second look to make sure it lines up with the citation specified in the v1.0.0 release.

I can also bring it to the team to see if they agree with maybe also duplicating this file into the main branch so people are able to immediately grab the citation information.

**Comment by juanpflores** [comment]
Oh! I didn't realize the file was on the open science branch. I 👍 with you that having it on the main branch might help people find it more easily and avoid committing the same mistake as I did.

**Comment by bressler95tops** [comment]
Thank you Juan, after polling for opinions from the team, it seems that they would like to address this by adding some reference material in the README file on the main branch.  Duplicating the citation file to the main branch would work fine, but we also believe that it should only be there when viewing the OS101 course material since the citation is in reference to that and not the rest of the material on the main branch.

So the compromise is just making sure that there is something obvious that guides users who would like to cite the course material with alternative formats. Expect some status updates on this soon and thanks for your help on this, we are always happy to receive feedback!

**Comment by juanpflores** [comment]
I'll close this issue and the pull request as well.
